name: BlockPortals
version: '${project.version}'
main: xyz.bobkinn.blockportals.BlockPortals
api-version: 1.13
author: BoBkiNN_
commands:
  switchdim:
    description: Switch dimension access
    permission: blockportals.switchdim
    aliases: ["switchdimension"]
  bpreload:
    description: Reload BlockPortals
    permission: blockportals.reload
    aliases:
      - blockportalsreload
      - blockportalsrl
      - bprl
